### ISSUE TITLE
Write-ObjectToSQL with GUID [Feature Request]

### ISSUE THREAD

**Issue by lw-schick** [JohnRoos/PowerShell#2]
**Use Case:**
I wanna use the function Write-ObjectToSQL to write some users from LDAP into SQL. I want to use `objectGUID` as a primary key.

**Need:**
I need the possibility to use a GUID as primary key.

**Comment by JohnRoos** [comment]
Good idea. This has now been implemented.

I have improved the GUID functionality so that they become unique identifiers in the target table instead.
I have also added an optional parameter called PrimaryKey which you now can use to create the primary key in the table.
