### ISSUE TITLE
Inserts for zero value int's result in NULL's

### ISSUE THREAD

**Issue by acheung456** [JohnRoos/PowerShell#4]
Looks like there is a boolean test where there should be a null test which is causing number data types that are zero valued to insert with NULL values.

Line: 789 (Write-ObjectToSQL.psm1)
`                    
if ($($InputObject.$key)){
                        if ($datatype -eq 'timespan' -or $datatype -eq 'System.TimeSpan') {
                            Write-Verbose "Timespan found ($key). Converting to ticks."
                            $null = $strBuilderValues.Append(", $(($InputObject.$key).Ticks)")
                        }else{
                            $null = $strBuilderValues.Append(", $($InputObject.$key)")
                        }
                    }else{
                        $null = $strBuilderValues.Append(", NULL")
                    }
`

`if ($($InputObject.$key))` will evaluate to false for any zero value, this causing ` $strBuilderValues.Append(", NULL")` to fill in a NULL for your insert string.  Just a heads up as I ran into this when filling in some columns of data that is usually 0,1,2 in value. Unless I am missing something that can modify the behavior so an actual zero goes in?

**Comment by JohnRoos** [comment]
Thank you for the feedback. Its easy to reproduce and should be quick to fix.
The same problem could exist in other parts of the module which I have to check. I will fix it as soon as I have some more time.

**Comment by JohnRoos** [comment]
Fixed
